### ISSUE TITLE
currently, the bash script is a very ugly hack which may need some tinkering to be fully functional

### ISSUE THREAD

**Issue by Mini-Ware** [Mini-Ware/CTF-Journey#10]
this is regarding the issue mentioned in the #9 pull request

**Comment by duckupus** [comment]
# Things that need to work for it to be fully functional
- [optional] read until prompt then input into stdin
- allow for multiple inputs to be inputted one by one, dont spin up more then one instance

**Comment by Mini-Ware** [comment]
Alright, I shall close this issue now.
